--
-- Table structure for table `register`
--
CREATE TABLE IF NOT EXISTS `register` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `FirstName` VARCHAR(128) NOT NULL,
  `LastName` VARCHAR(128) NOT NULL,
  `Email` VARCHAR(128) NOT NULL,
  `Company` VARCHAR(128) NULL DEFAULT NULL,
  `Skype` VARCHAR(128) NOT NULL,
  `Website` VARCHAR(128) NULL DEFAULT NULL,
  `Message` VARCHAR(500) NULL DEFAULT NULL,
  `CreatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP
);